#!/bin/bash

FILENAME="./assess"
BITS="100000"
INPUT_OPTION="0"
SOURCE="4thByte7thBit.bin"
TESTS="1"
PARAMETER_ADJUSTMENTS="0"
BITSTREAMS="50"
FILE_FORMAT="1"

echo "Executing '$FILENAME'..."
"$FILENAME" "$BITS" << EOF
$INPUT_OPTION  $SOURCE $TESTS $PARAMETER_ADJUSTMENTS $BITSTREAMS $FILE_FORMAT
EOF